### ISSUE TITLE
dockerhub has a error in docker run

### ISSUE THREAD

**Issue by 3fong** [rongfengliang/cloudbeaver-docker#3]
hi,rong!
when i excute the command 'docker run' find a error in your dockerhub,
your command like that:
docker run -d -p  8978:8978  dalongrong/dalongrong/cloudbeaver

but the right command i think should be under:
docker run -d -p  8978:8978  dalongrong/cloudbeaver

hope u notice the issue,thanks!

**Comment by rongfengliang** [comment]
@liulei3  fixed!
